In [3]:
import pandas as pd
import numpy as np

In [4]:
music = pd.read_csv('features_30_sec.csv')
music.shape

(1000, 60)

In [5]:
music.describe()

,length,chroma_stft_mean,chroma_stft_var,rms_mean,rms_var,spectral_centroid_mean,spectral_centroid_var,spectral_bandwidth_mean,spectral_bandwidth_var,rolloff_mean,...,mfcc16_mean,mfcc16_var,mfcc17_mean,mfcc17_var,mfcc18_mean,mfcc18_var,mfcc19_mean,mfcc19_var,mfcc20_mean,mfcc20_var
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.000000,...,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,662030.846000,0.378682,0.086340,0.130930,0.003051,2201.780898,4.696916e+05,2242.541070,137079.155165,4571.549304,...,1.148144,60.730958,-3.966028,62.633624,0.507696,63.712586,-2.328761,66.231930,-1.095348,70.126096
std,1784.073992,0.081705,0.007735,0.065683,0.003634,715.960600,4.008995e+05,526.316473,96455.666326,1574.791602,...,4.578948,33.781951,4.549697,33.479172,3.869105,34.401977,3.755957,37.174631,3.837007,45.228512
min,660000.000000,0.171939,0.044555,0.005276,0.000004,570.040355,7.911251e+03,898.066208,10787.185064,749.140636,...,-15.693844,9.169314,-17.234728,13.931521,-11.963694,15.420555,-18.501955,13.487622,-19.929634,7.956583
25%,661504.000000,0.319562,0.082298,0.086657,0.000942,1627.697311,1.843505e+05,1907.240605,67376.554428,3380.069642,...,-1.863280,40.376442,-7.207225,40.830875,-2.007015,41.884240,-4.662925,41.710184,-3.368996,42.372865
50%,661794.000000,0.383148,0.086615,0.122443,0.001816,2209.263090,3.384862e+05,2221.392843,111977.548036,4658.524473,...,1.212809,52.325077,-4.065605,54.717674,0.669643,54.804890,-2.393862,57.423059,-1.166289,59.186117
75%,661794.000000,0.435942,0.091256,0.175682,0.003577,2691.294667,6.121479e+05,2578.469836,182371.576801,5533.810460,...,4.359662,71.691755,-0.838737,75.040838,3.119212,75.385832,0.150573,78.626444,1.312615,85.375374
max,675808.000000,0.663685,0.108111,0.397973,0.027679,4435.243901,3.036843e+06,3509.646417,694784.811549,8677.672688,...,13.457150,392.932373,11.482946,406.058868,15.388390,332.905426,14.694924,393.161987,15.369627,506.065155

In [6]:
music = music.drop(columns=['length'])

In [10]:
colonnes = [c for c in music.columns if c not in ('filename','label')]
print(len(colonnes))

57

In [11]:
music.head(10)

,filename,chroma_stft_mean,chroma_stft_var,rms_mean,rms_var,spectral_centroid_mean,spectral_centroid_var,spectral_bandwidth_mean,spectral_bandwidth_var,rolloff_mean,...,mfcc16_var,mfcc17_mean,mfcc17_var,mfcc18_mean,mfcc18_var,mfcc19_mean,mfcc19_var,mfcc20_mean,mfcc20_var,label
0,blues.00000.wav,0.350088,0.088757,0.130228,0.002827,1784.165850,1.297741e+05,2002.449060,85882.761315,3805.839606,...,52.420910,-1.690215,36.524071,-0.408979,41.597103,-2.303523,55.062923,1.221291,46.936035,blues
1,blues.00001.wav,0.340914,0.094980,0.095948,0.002373,1530.176679,3.758501e+05,2039.036516,213843.755497,3550.522098,...,55.356403,-0.731125,60.314529,0.295073,48.120598,-0.283518,51.106190,0.531217,45.786282,blues
2,blues.00002.wav,0.363637,0.085275,0.175570,0.002746,1552.811865,1.564676e+05,1747.702312,76254.192257,3042.260232,...,40.598766,-7.729093,47.639427,-1.816407,52.382141,-3.439720,46.639660,-2.231258,30.573025,blues
3,blues.00003.wav,0.404785,0.093999,0.141093,0.006346,1070.106615,1.843559e+05,1596.412872,166441.494769,2184.745799,...,44.427753,-3.319597,50.206673,0.636965,37.319130,-0.619121,37.259739,-3.407448,31.949339,blues
4,blues.00004.wav,0.308526,0.087841,0.091529,0.002303,1835.004266,3.433999e+05,1748.172116,88445.209036,3579.757627,...,86.099236,-5.454034,75.269707,-0.916874,53.613918,-4.404827,62.910812,-11.703234,55.195160,blues
5,blues.00005.wav,0.302456,0.087532,0.103494,0.003981,1831.993940,1.030482e+06,1729.653287,201910.508633,3481.517592,...,72.549225,-1.838263,68.702026,-2.783800,42.447453,-3.047909,39.808784,-8.109991,46.311005,blues
6,blues.00006.wav,0.291328,0.093981,0.141874,0.008803,1459.366472,4.378594e+05,1389.009131,185023.239545,2795.610963,...,83.248245,-10.913176,56.902153,-6.971336,38.231800,-3.436505,48.235741,-6.483466,70.170364,blues
7,blues.00007.wav,0.307955,0.092903,0.131822,0.005531,1451.667066,4.495682e+05,1577.270941,168211.938804,2954.836760,...,70.438438,-10.568935,52.090893,-10.784515,60.461330,-4.690678,65.547516,-8.630722,56.401436,blues
8,blues.00008.wav,0.408879,0.086512,0.142416,0.001507,1719.368948,1.632828e+05,2031.740381,105542.718193,3782.316288,...,50.563751,-7.041824,28.894934,2.695248,36.889568,3.412305,33.698597,-2.715692,36.418430,blues
9,blues.00009.wav,0.273950,0.092316,0.081314,0.004347,1817.150863,2.982361e+05,1973.773306,114070.112591,3943.490565,...,59.314602,-1.916804,58.418438,-2.292661,83.205231,2.881967,77.082222,-4.235203,91.468811,blues

In [13]:
print(music.duplicated(subset=colonnes).sum())

14

In [14]:
masque = music.duplicated(subset=colonnes, keep=False)
print(music[masque].sort_values(colonnes[0])[['filename', 'label']])

             filename   label
754     pop.00054.wav     pop
760     pop.00060.wav     pop
445  hiphop.00045.wav  hiphop
439  hiphop.00039.wav  hiphop
634   metal.00034.wav   metal
694   metal.00094.wav   metal
478  hiphop.00078.wav  hiphop
476  hiphop.00076.wav  hiphop
666   metal.00066.wav   metal
645   metal.00045.wav   metal
642   metal.00042.wav   metal
663   metal.00063.wav   metal
664   metal.00064.wav   metal
643   metal.00043.wav   metal
399   disco.00099.wav   disco
398   disco.00098.wav   disco
767     pop.00067.wav     pop
771     pop.00071.wav     pop
641   metal.00041.wav   metal
662   metal.00062.wav   metal
916    rock.00016.wav    rock
658   metal.00058.wav   metal
644   metal.00044.wav   metal
665   metal.00065.wav   metal
881  reggae.00081.wav  reggae
882  reggae.00082.wav  reggae
661   metal.00061.wav   metal
640   metal.00040.wav   metal

In [15]:
music = music[~music['filename'].isin(['rock.00016.wav', 'metal.00058.wav'])]

In [16]:
music = music.drop_duplicates(subset=colonnes, keep='first')

In [17]:
music = music.reset_index(drop=True)

In [18]:
print(music.duplicated(subset=colonnes).sum())

0

In [19]:
music.shape

(985, 59)

In [ ]:
import numpy as np

# Découpage stratifié 80 % apprentissage / 20 % test, graine fixe
rng = np.random.default_rng(42)
idx_train, idx_test = [], []

for genre, groupe in music.groupby('label'):
    idx = rng.permutation(groupe.index.to_numpy())
    n_test = int(round(len(idx) * 0.2))
    idx_test.extend(idx[:n_test])   # 20 % pour le test
    idx_train.extend(idx[n_test:])  # 80 % pour l'apprentissage

train = music.loc[idx_train]
test = music.loc[idx_test]

print(train.shape, test.shape)  # (787, 59) (198, 59)

(787, 59) (198, 59)

In [21]:
print("Total :", len(train) + len(test))  # 985
print(test['label'].value_counts().sort_index())
print((test['label'].value_counts() / music['label'].value_counts()).sort_index())

Total : 985
label
blues        20
classical    20
country      20
disco        20
hiphop       20
jazz         20
metal        18
pop          20
reggae       20
rock         20
Name: count, dtype: int64
label
blues        0.200000
classical    0.200000
country      0.200000
disco        0.202020
hiphop       0.204082
jazz         0.200000
metal        0.195652
pop          0.204082
reggae       0.202020
rock         0.202020
Name: count, dtype: float64

In [24]:
music.head(10)

,filename,chroma_stft_mean,chroma_stft_var,rms_mean,rms_var,spectral_centroid_mean,spectral_centroid_var,spectral_bandwidth_mean,spectral_bandwidth_var,rolloff_mean,...,mfcc16_var,mfcc17_mean,mfcc17_var,mfcc18_mean,mfcc18_var,mfcc19_mean,mfcc19_var,mfcc20_mean,mfcc20_var,label
0,blues.00000.wav,0.350088,0.088757,0.130228,0.002827,1784.165850,1.297741e+05,2002.449060,85882.761315,3805.839606,...,52.420910,-1.690215,36.524071,-0.408979,41.597103,-2.303523,55.062923,1.221291,46.936035,blues
1,blues.00001.wav,0.340914,0.094980,0.095948,0.002373,1530.176679,3.758501e+05,2039.036516,213843.755497,3550.522098,...,55.356403,-0.731125,60.314529,0.295073,48.120598,-0.283518,51.106190,0.531217,45.786282,blues
2,blues.00002.wav,0.363637,0.085275,0.175570,0.002746,1552.811865,1.564676e+05,1747.702312,76254.192257,3042.260232,...,40.598766,-7.729093,47.639427,-1.816407,52.382141,-3.439720,46.639660,-2.231258,30.573025,blues
3,blues.00003.wav,0.404785,0.093999,0.141093,0.006346,1070.106615,1.843559e+05,1596.412872,166441.494769,2184.745799,...,44.427753,-3.319597,50.206673,0.636965,37.319130,-0.619121,37.259739,-3.407448,31.949339,blues
4,blues.00004.wav,0.308526,0.087841,0.091529,0.002303,1835.004266,3.433999e+05,1748.172116,88445.209036,3579.757627,...,86.099236,-5.454034,75.269707,-0.916874,53.613918,-4.404827,62.910812,-11.703234,55.195160,blues
5,blues.00005.wav,0.302456,0.087532,0.103494,0.003981,1831.993940,1.030482e+06,1729.653287,201910.508633,3481.517592,...,72.549225,-1.838263,68.702026,-2.783800,42.447453,-3.047909,39.808784,-8.109991,46.311005,blues
6,blues.00006.wav,0.291328,0.093981,0.141874,0.008803,1459.366472,4.378594e+05,1389.009131,185023.239545,2795.610963,...,83.248245,-10.913176,56.902153,-6.971336,38.231800,-3.436505,48.235741,-6.483466,70.170364,blues
7,blues.00007.wav,0.307955,0.092903,0.131822,0.005531,1451.667066,4.495682e+05,1577.270941,168211.938804,2954.836760,...,70.438438,-10.568935,52.090893,-10.784515,60.461330,-4.690678,65.547516,-8.630722,56.401436,blues
8,blues.00008.wav,0.408879,0.086512,0.142416,0.001507,1719.368948,1.632828e+05,2031.740381,105542.718193,3782.316288,...,50.563751,-7.041824,28.894934,2.695248,36.889568,3.412305,33.698597,-2.715692,36.418430,blues
9,blues.00009.wav,0.273950,0.092316,0.081314,0.004347,1817.150863,2.982361e+05,1973.773306,114070.112591,3943.490565,...,59.314602,-1.916804,58.418438,-2.292661,83.205231,2.881967,77.082222,-4.235203,91.468811,blues

In [25]:
music.shape

(985, 59)

In [26]:
import numpy as np

# 1. Normalisation : moyenne et écart-type calculés sur le TRAIN uniquement
moyenne = train[colonnes].mean()
ecart = train[colonnes].std()
ecart[ecart == 0] = 1  # sécurité : caractéristique constante

X_train = ((train[colonnes] - moyenne) / ecart).to_numpy()
X_test = ((test[colonnes] - moyenne) / ecart).to_numpy()

# 2. Encodage des genres en 0..9 (ordre alphabétique)
genres = sorted(music['label'].unique())
code = {g: i for i, g in enumerate(genres)}
y_train = train['label'].map(code).to_numpy()
y_test = test['label'].map(code).to_numpy()

# 3. Vérifications
print("X_train :", X_train.shape)  # (787, 57)
print("X_test  :", X_test.shape)   # (198, 57)
print("y_train :", y_train.shape, "| y_test :", y_test.shape)
print("Genres  :", genres)
print("Moyenne X_train (≈ 0) :", X_train.mean())
print("Écart-type X_train (≈ 1) :", X_train.std())
print("NaN dans X_train :", np.isnan(X_train).sum(), "| dans X_test :", np.isnan(X_test).sum())

X_train : (787, 57)
X_test  : (198, 57)
y_train : (787,) | y_test : (198,)
Genres  : ['blues', 'classical', 'country', 'disco', 'hiphop', 'jazz', 'metal', 'pop', 'reggae', 'rock']
Moyenne X_train (≈ 0) : -2.8590241379588954e-17
Écart-type X_train (≈ 1) : 0.9993644740381281
NaN dans X_train : 0 | dans X_test : 0

In [29]:
import os
os.makedirs('data', exist_ok=True)

# La table nettoyée (985 morceaux) : dans ce notebook elle s'appelle music
music.to_csv('data/music_propre.csv', index=False)

# Les tableaux prêts pour B et C
np.save('data/X_train.npy', X_train)
np.save('data/X_test.npy', X_test)
np.save('data/y_train.npy', y_train)
np.save('data/y_test.npy', y_test)

In [30]:
import os
print(os.listdir('data'))

['y_train.npy', 'music_propre.csv', 'y_test.npy', 'X_test.npy', 'X_train.npy']

In [31]:
import numpy as np

def precision(y_vrai, y_pred):
    """Pourcentage de bonnes réponses."""
    return float(np.mean(np.asarray(y_vrai) == np.asarray(y_pred)))

def matrice_confusion(y_vrai, y_pred, n_classes=10):
    """Lignes = vraie classe, colonnes = classe prédite."""
    mat = np.zeros((n_classes, n_classes), dtype=int)
    for vrai, pred in zip(y_vrai, y_pred):
        mat[int(vrai), int(pred)] += 1
    return mat

# Test immédiat avec des prédictions factices (toujours blues = 0)
y_faux = np.zeros_like(y_test)
print("Précision (factice) :", precision(y_test, y_faux))
print(matrice_confusion(y_test, y_faux))

Précision (factice) : 0.10101010101010101
[[20  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [18  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]]